<?php
require_once __DIR__.'/../../includes/staff/feature-tools.php'; require_permission('materials.view'); verify_csrf(); $pdo=staff_db(); feature_table($pdo,'bills_of_materials'); $staff=current_staff();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=fpost('action');
 if($action==='create'){ $pid=fint('project_id'); if(!$pid){flash('error','Choose a project.');staff_redirect('staff/pages/bom.php');} $code=op_code('BOM'); $q=$pdo->prepare('INSERT INTO bills_of_materials(bom_code,project_id,status,notes,created_by) VALUES(?,?,?,?,?)');$q->execute([$code,$pid,'draft',fpost('notes')?:null,$staff['id']]); flash('success','Bill of materials created.'); }
 if($action==='add_item'){ $bom=fint('bom_id');$mat=fint('material_id');$qty=fnum('required_qty');$w=fnum('waste_percent');$m=db_one($pdo,'SELECT unit,unit_cost FROM materials WHERE id=?',[$mat]); if($bom&&$mat&&$m){$purchase=$qty*(1+$w/100);$line=$purchase*(float)$m['unit_cost'];$q=$pdo->prepare('INSERT INTO bom_items(bom_id,material_id,required_qty,waste_percent,purchase_qty,unit,unit_cost,line_cost,source) VALUES(?,?,?,?,?,?,?,?,?)');$q->execute([$bom,$mat,$qty,$w,$purchase,$m['unit'],$m['unit_cost'],$line,'manual']);$pdo->prepare('UPDATE bills_of_materials SET material_cost=(SELECT COALESCE(SUM(line_cost),0) FROM bom_items WHERE bom_id=?),total_cost=(SELECT COALESCE(SUM(line_cost),0) FROM bom_items WHERE bom_id=?),status="calculated" WHERE id=?')->execute([$bom,$bom,$bom]);flash('success','Material added to BOM.');}}
 staff_redirect('staff/pages/bom.php');
}
$projects=project_options($pdo);$materials=material_options($pdo);$boms=db_rows($pdo,'SELECT b.*,p.project_code,p.name project_name,(SELECT COUNT(*) FROM bom_items i WHERE i.bom_id=b.id) item_count FROM bills_of_materials b JOIN projects p ON p.id=b.project_id ORDER BY b.updated_at DESC');$pageTitle='Bill of Materials';require __DIR__.'/../../includes/staff/header.php'; module_head('Costing','Bill of Materials','Turn project requirements into purchase quantities and material cost.');?>
<div class="split-grid"><section class="staff-panel"><h2>Create BOM</h2><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="create"><label>Project<select name="project_id" required><option value="">Choose...</option><?php foreach($projects as $p):?><option value="<?=$p['id']?>"><?=h($p['project_code'].' · '.$p['name'])?></option><?php endforeach?></select></label><label>Notes<textarea name="notes"></textarea></label><button class="btn primary">Create BOM</button></form></section><section class="staff-panel"><h2>Add material</h2><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="add_item"><label>BOM<select name="bom_id" required><?php foreach($boms as $b):?><option value="<?=$b['id']?>"><?=h($b['bom_code'].' · '.$b['project_name'])?></option><?php endforeach?></select></label><label>Material<select name="material_id" required><?php foreach($materials as $m):?><option value="<?=$m['id']?>"><?=h($m['name'].' · RM '.number_format($m['unit_cost'],2).'/'.$m['unit'])?></option><?php endforeach?></select></label><div class="two"><label>Required qty<input type="number" step=".001" name="required_qty" required></label><label>Waste %<input type="number" step=".01" name="waste_percent" value="8"></label></div><button class="btn">Add material</button></form></section></div>
<section class="staff-panel table-panel"><table><thead><tr><th>BOM</th><th>Project</th><th>Status</th><th>Items</th><th>Total cost</th><th>Updated</th></tr></thead><tbody><?php foreach($boms as $b):?><tr><td><b><?=h($b['bom_code'])?></b></td><td><?=h($b['project_code'].' · '.$b['project_name'])?></td><td><span class="pill"><?=h($b['status'])?></span></td><td><?=$b['item_count']?></td><td>RM <?=number_format($b['total_cost'],2)?></td><td><?=h(date('j M Y',strtotime($b['updated_at'])))?></td></tr><?php endforeach?></tbody></table></section><?php module_end();require __DIR__.'/../../includes/staff/footer.php';?>