<?php
require_once __DIR__.'/../../includes/staff/operations.php';require_login();verify_csrf();$pdo=staff_db();$staff=current_staff();$id=(int)($_GET['id']??0);
$q=$pdo->prepare("SELECT c.*,CONCAT(s.first_name,' ',COALESCE(s.last_name,'')) assigned_name FROM customers c LEFT JOIN staff s ON s.id=c.assigned_to WHERE c.id=?");$q->execute([$id]);$customer=$q->fetch();if(!$customer){http_response_code(404);exit('Customer not found');}
$leadQ=$pdo->prepare('SELECT * FROM leads WHERE customer_id=? LIMIT 1');$leadQ->execute([$id]);$lead=$leadQ->fetch();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $action=$_POST['action']??'';
 if($action==='update_customer'){$q=$pdo->prepare('UPDATE customers SET name=?,phone=?,email=?,address=?,lead_source=?,interested_service=?,assigned_to=?,status=?,notes=? WHERE id=?');$assigned=$_POST['assigned_to']!==''?(int)$_POST['assigned_to']:null;$q->execute([trim($_POST['name']),trim($_POST['phone'])?:null,trim($_POST['email'])?:null,trim($_POST['address'])?:null,trim($_POST['lead_source'])?:null,trim($_POST['interested_service'])?:null,$assigned,$_POST['status'],trim($_POST['notes'])?:null,$id]);if($lead){$pdo->prepare('UPDATE leads SET assigned_to=? WHERE id=?')->execute([$assigned,$lead['id']]);}flash('success','Customer updated.');staff_redirect('staff/pages/customer-view.php?id='.$id);}
 if($action==='lead_stage' && $lead){$stage=$_POST['stage'];$pdo->prepare('UPDATE leads SET stage=?,estimated_value=?,probability=?,lost_reason=? WHERE id=?')->execute([$stage,(float)$_POST['estimated_value'],(int)$_POST['probability'],trim($_POST['lost_reason'])?:null,$lead['id']]);if($stage==='won')$pdo->prepare("UPDATE customers SET status='active' WHERE id=?")->execute([$id]);flash('success','Lead stage updated.');staff_redirect('staff/pages/customer-view.php?id='.$id);}
 if($action==='follow_up'){$when=str_replace('T',' ',$_POST['follow_up_at']);$q=$pdo->prepare('INSERT INTO follow_ups(customer_id,lead_id,assigned_to,follow_up_at,reason,notes,created_by) VALUES(?,?,?,?,?,?,?)');$q->execute([$id,$lead['id']??null,$_POST['assigned_to']!==''?(int)$_POST['assigned_to']:$staff['id'],$when,trim($_POST['reason']),trim($_POST['follow_notes'])?:null,$staff['id']]);if($lead)$pdo->prepare('UPDATE leads SET next_follow_up_at=? WHERE id=?')->execute([$when,$lead['id']]);flash('success','Follow-up scheduled.');staff_redirect('staff/pages/customer-view.php?id='.$id);}
 if($action==='complete_follow'){$fid=(int)$_POST['follow_id'];$pdo->prepare("UPDATE follow_ups SET status='completed',completed_at=NOW() WHERE id=? AND customer_id=?")->execute([$fid,$id]);flash('success','Follow-up completed.');staff_redirect('staff/pages/customer-view.php?id='.$id);}
 if($action==='create_project'){$code=op_code('PRJ');$q=$pdo->prepare('INSERT INTO projects(project_code,customer_id,name,project_type,status,assigned_manager,site_address,estimated_value,start_date,target_date,notes,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$q->execute([$code,$id,trim($_POST['project_name']),trim($_POST['project_type'])?:null,'consultation',$_POST['assigned_manager']!==''?(int)$_POST['assigned_manager']:null,trim($_POST['site_address'])?:$customer['address'],(float)$_POST['project_value'],$_POST['start_date']?:null,$_POST['target_date']?:null,trim($_POST['project_notes'])?:null,$staff['id']]);$pid=(int)$pdo->lastInsertId();project_activity($pdo,$pid,'project_created','Project created','Created from '.$customer['name'].' CRM profile.');flash('success','Project created.');staff_redirect('staff/pages/project-view.php?id='.$pid);}
}
$staffRows=$pdo->query("SELECT id,first_name,last_name FROM staff WHERE is_active=1 ORDER BY first_name,last_name")->fetchAll();$fq=$pdo->prepare("SELECT f.*,CONCAT(s.first_name,' ',COALESCE(s.last_name,'')) staff_name FROM follow_ups f LEFT JOIN staff s ON s.id=f.assigned_to WHERE f.customer_id=? ORDER BY f.follow_up_at DESC");$fq->execute([$id]);$followups=$fq->fetchAll();$pq=$pdo->prepare('SELECT * FROM projects WHERE customer_id=? ORDER BY created_at DESC');$pq->execute([$id]);$projects=$pq->fetchAll();$pageTitle=$customer['name'];require __DIR__.'/../../includes/staff/header.php';?>
<main class="staff-content"><div class="page-head"><div><p class="eyebrow"><?= h($customer['customer_code']) ?></p><h1><?= h($customer['name']) ?></h1><p class="muted"><?= h($customer['phone']?:'No phone') ?> · <?= h($customer['email']?:'No email') ?></p></div><div class="actions"><a class="btn" href="<?= h(ideare_root_url('staff/pages/customers.php')) ?>">Back to customers</a></div></div>
<div class="tabs"><a href="#profile">Profile</a><a href="#lead">Lead</a><a href="#followups">Follow-ups</a><a href="#projects">Projects</a></div>
<div class="split-grid"><section class="staff-panel" id="profile"><h2>Customer profile</h2><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="update_customer"><div class="two"><label>Name<input name="name" value="<?= h($customer['name']) ?>" required></label><label>Phone<input name="phone" value="<?= h($customer['phone']) ?>"></label></div><div class="two"><label>Email<input name="email" value="<?= h($customer['email']) ?>"></label><label>Lead source<input name="lead_source" value="<?= h($customer['lead_source']) ?>"></label></div><label>Address<textarea name="address"><?= h($customer['address']) ?></textarea></label><div class="two"><label>Interested service<input name="interested_service" value="<?= h($customer['interested_service']) ?>"></label><label>Status<select name="status"><?php foreach(['lead','active','inactive','completed'] as $x):?><option value="<?= $x ?>" <?= $customer['status']===$x?'selected':'' ?>><?= ucfirst($x) ?></option><?php endforeach;?></select></label></div><label>Assigned staff<select name="assigned_to"><option value="">Unassigned</option><?php foreach($staffRows as $s):?><option value="<?= $s['id'] ?>" <?= (int)$customer['assigned_to']===(int)$s['id']?'selected':'' ?>><?= h(trim($s['first_name'].' '.$s['last_name'])) ?></option><?php endforeach;?></select></label><label>Internal notes<textarea name="notes"><?= h($customer['notes']) ?></textarea></label><button class="btn primary">Save profile</button></form></section>
<section class="staff-panel" id="lead"><h2>Sales pipeline</h2><?php if($lead):?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="lead_stage"><label>Stage<select name="stage"><?php foreach(lead_stages() as $k=>$v):?><option value="<?= h($k) ?>" <?= $lead['stage']===$k?'selected':'' ?>><?= h($v) ?></option><?php endforeach;?></select></label><div class="two"><label>Estimated value (RM)<input type="number" step=".01" name="estimated_value" value="<?= h($lead['estimated_value']) ?>"></label><label>Probability %<input type="number" min="0" max="100" name="probability" value="<?= (int)$lead['probability'] ?>"></label></div><label>Lost reason<textarea name="lost_reason"><?= h($lead['lost_reason']) ?></textarea></label><button class="btn">Update pipeline</button></form><?php endif;?></section></div>
<div class="split-grid"><section class="staff-panel" id="followups"><h2>Schedule follow-up</h2><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="follow_up"><label>Date & time<input type="datetime-local" name="follow_up_at" required></label><label>Reason<input name="reason" placeholder="Quotation follow-up" required></label><label>Assigned staff<select name="assigned_to"><option value="">Me</option><?php foreach($staffRows as $s):?><option value="<?= $s['id'] ?>"><?= h(trim($s['first_name'].' '.$s['last_name'])) ?></option><?php endforeach;?></select></label><label>Notes<textarea name="follow_notes"></textarea></label><button class="btn primary">Schedule</button></form><div class="list"><?php foreach($followups as $f):?><div class="list-row"><div><b><?= h($f['reason']) ?></b><small><?= h(date('j M Y, g:i A',strtotime($f['follow_up_at']))) ?> · <?= h($f['staff_name']?:'Unassigned') ?> · <?= h($f['status']) ?></small></div><?php if($f['status']==='pending'):?><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="complete_follow"><input type="hidden" name="follow_id" value="<?= $f['id'] ?>"><button class="btn">Complete</button></form><?php endif;?></div><?php endforeach;?></div></section>
<section class="staff-panel" id="projects"><h2>Start project</h2><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="create_project"><label>Project name<input name="project_name" value="<?= h(($customer['interested_service']?:'Cabinet').' project') ?>" required></label><div class="two"><label>Type<input name="project_type" value="<?= h($customer['interested_service']) ?>"></label><label>Value (RM)<input type="number" step=".01" name="project_value" value="<?= h($lead['estimated_value']??0) ?>"></label></div><label>Site address<textarea name="site_address"><?= h($customer['address']) ?></textarea></label><div class="two"><label>Start date<input type="date" name="start_date"></label><label>Target date<input type="date" name="target_date"></label></div><label>Project manager<select name="assigned_manager"><option value="">Unassigned</option><?php foreach($staffRows as $s):?><option value="<?= $s['id'] ?>"><?= h(trim($s['first_name'].' '.$s['last_name'])) ?></option><?php endforeach;?></select></label><label>Notes<textarea name="project_notes"></textarea></label><button class="btn primary">Create project</button></form><div class="list"><?php foreach($projects as $p):?><div class="list-row"><div><a href="<?= h(ideare_root_url('staff/pages/project-view.php?id='.$p['id'])) ?>"><b><?= h($p['name']) ?></b></a><small><?= h($p['project_code']) ?> · <?= h(str_replace('_',' ',$p['status'])) ?></small></div><strong><?= money($p['estimated_value']) ?></strong></div><?php endforeach;?></div></section></div></main>
<?php require __DIR__.'/../../includes/staff/footer.php'; ?>
