<?php
require_once __DIR__.'/../../includes/staff/auth.php';require_permission('leave.view_own');verify_csrf();$pdo=staff_db();$staff=current_staff();$types=$pdo->query("SELECT * FROM leave_types WHERE is_active=1 ORDER BY name")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'&&can('leave.submit')){$s=$pdo->prepare("INSERT INTO leave_requests(staff_id,leave_type_id,start_date,end_date,total_days,reason) VALUES(?,?,?,?,?,?)");$s->execute([$staff['id'],$_POST['leave_type_id'],$_POST['start_date'],$_POST['end_date'],max(1,(strtotime($_POST['end_date'])-strtotime($_POST['start_date']))/86400+1),trim($_POST['reason'])]);flash('success','Request submitted.');staff_redirect('staff/pages/leave.php');}
$s=$pdo->prepare("SELECT r.*,lt.name detail FROM leave_requests r JOIN leave_types lt ON lt.id=r.leave_type_id WHERE r.staff_id=? ORDER BY r.created_at DESC");$s->execute([$staff['id']]);$rows=$s->fetchAll();
$pageTitle='Leave';require __DIR__.'/../../includes/staff/header.php';?>
<main class="staff-content"><div class="page-head"><div><p class="eyebrow">Requests</p><h1>Leave</h1></div></div><div class="split-grid"><section class="staff-panel"><h2>New request</h2><form method="post"><?= csrf_field() ?>
    <label>Leave type<select name="leave_type_id"><?php foreach($types as $t):?><option value="<?= $t['id'] ?>"><?= h($t['name']) ?></option><?php endforeach;?></select></label>
    <div class="two"><label>Start<input type="date" name="start_date" required></label><label>End<input type="date" name="end_date" required></label></div>
    <label>Reason<textarea name="reason" required></textarea></label>
    <button class="btn primary">Submit request</button></form></section><section class="staff-panel table-panel"><h2>My requests</h2><table><thead><tr><th>Details</th><th>Status</th><th>Created</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?= h($r['detail']??$r['reason']??'') ?></td><td><span class="pill <?= h($r['status']) ?>"><?= h($r['status']) ?></span></td><td><?= h(date('j M Y',strtotime($r['created_at']))) ?></td></tr><?php endforeach;?></tbody></table></section></div></main><?php require __DIR__.'/../../includes/staff/footer.php';?>